# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Sector short name')),
                ('title', models.CharField(max_length=32)),
                ('body_text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
