# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_num', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('term', models.IntegerField(choices=[(1, '1 - short'), (2, '2 - short-medium'), (3, '3 - medium'), (4, '4 - short-medium-long'), (5, '5 - medium-long'), (6, '6 - long')], default=0)),
                ('responsible', models.CharField(blank=True, default='', max_length=255)),
                ('stakeholder', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='goal',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Sector'),
        ),
    ]
