# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20160616_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(0, '0 - undetermined'), (1, '1 - short'), (2, '2 - short-medium'), (3, '3 - medium'), (5, '5 - medium-long'), (6, '6 - long')], default=0)),
                ('rec_num', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('responsible', models.CharField(blank=True, default='', max_length=255)),
                ('stakeholder', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='term',
            field=models.IntegerField(choices=[(0, '0 - undetermined'), (1, '1 - short'), (2, '2 - short-medium'), (3, '3 - medium'), (5, '5 - medium-long'), (6, '6 - long')], default=0),
        ),
        migrations.AddField(
            model_name='rec',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Goal'),
        ),
    ]
