# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20160617_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(0, '0 - undetermined'), (1, '1 - short'), (2, '2 - short-medium'), (3, '3 - medium'), (5, '5 - medium-long'), (6, '6 - long')], default=0)),
                ('action_num', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('related', models.CharField(blank=True, default='', max_length=128)),
                ('responsible', models.CharField(blank=True, default='', max_length=128)),
                ('stakeholder', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['id'], 'verbose_name': 'Recommendation'},
        ),
        migrations.AddField(
            model_name='action',
            name='rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Rec'),
        ),
    ]
