# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20160617_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='related',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
