# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, to='plan.Tag', verbose_name='Tags for this item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
