# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20160619_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='background',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='background',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='progress',
        ),
        migrations.AlterField(
            model_name='action',
            name='background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='metrics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='progress',
            field=models.TextField(blank=True, default=''),
        ),
    ]
