# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20160628_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Organization short name')),
                ('name', models.CharField(max_length=128)),
                ('link_url', models.CharField(blank=True, default='', max_length=128)),
                ('town', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='term',
            field=models.IntegerField(choices=[(0, 'undetermined'), (1, 'short'), (2, 'short-medium'), (3, 'medium'), (4, 'short-medium-long'), (5, 'medium-long'), (6, 'long')], default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='term',
            field=models.IntegerField(choices=[(0, 'undetermined'), (1, 'short'), (2, 'short-medium'), (3, 'medium'), (4, 'short-medium-long'), (5, 'medium-long'), (6, 'long')], default=0),
        ),
        migrations.AlterField(
            model_name='rec',
            name='term',
            field=models.IntegerField(choices=[(0, 'undetermined'), (1, 'short'), (2, 'short-medium'), (3, 'medium'), (4, 'short-medium-long'), (5, 'medium-long'), (6, 'long')], default=0),
        ),
    ]
