# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20160628_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='plan.Organization', verbose_name='Organizations for this item'),
        ),
    ]
