# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_action_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='actions',
            field=models.ManyToManyField(blank=True, to='plan.Action', verbose_name='Other actions related to this action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='plan.Organization', verbose_name='Organizations for this action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, to='plan.Tag', verbose_name='Tags for this action'),
        ),
    ]
