# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20160629_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='organizations',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
