# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_action_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='credit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
