# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_sector_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Story image name'),
        ),
    ]
