# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0001_initial'),
        ('plan', '0018_goal_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='menu',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AddField(
            model_name='goal',
            name='menu',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AddField(
            model_name='rec',
            name='menu',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AddField(
            model_name='sector',
            name='menu',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
    ]
