# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20161116_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
    ]
