# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_auto_20161116_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='credit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Image credit'),
        ),
    ]
