# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0021_goal_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='short_title',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sector',
            name='title',
            field=models.CharField(max_length=48),
        ),
    ]
