# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='home_blurb',
            field=models.TextField(blank=True, default='', verbose_name='Home page blurb'),
        ),
    ]
