# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Story short name')),
                ('second_image', models.CharField(blank=True, default='', max_length=32)),
                ('alt_shortname', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('credit', models.CharField(blank=True, default='', max_length=64)),
                ('body_text', models.TextField(blank=True, default='')),
                ('related', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
