# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20160629_1155'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='story',
            name='actions',
            field=models.ManyToManyField(blank=True, to='plan.Action', verbose_name='Actions related to this story'),
        ),
    ]
