# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20161115_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['ordinal', 'id']},
        ),
    ]
