# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Project short name')),
                ('title', models.CharField(max_length=48)),
                ('narrative', models.TextField(blank=True, default='')),
            ],
        ),
    ]
