# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_action_organizations'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actions',
            field=models.ManyToManyField(blank=True, to='plan.Action', verbose_name='Actions related to this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_action_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='menu_blurb',
            field=models.TextField(blank=True, default=''),
        ),
    ]
