# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161107_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['ordinal']},
        ),
        migrations.AddField(
            model_name='project',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Order in Menu'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Draft'), (1, '1 - Display')], default=0),
        ),
    ]
