# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161107_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='narrative',
            new_name='body_text',
        ),
    ]
