# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20161130_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='credit1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='credit2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='credit3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.AlterField(
            model_name='project',
            name='menu_blurb',
            field=models.TextField(blank=True, default='', help_text="Appears under title on menu list. Don't add paragraph markup."),
        ),
    ]
