# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161130_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_num', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='projects')),
                ('credit', models.CharField(blank=True, default='', max_length=64, verbose_name='Image credit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
