# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_num', models.IntegerField()),
                ('title', models.CharField(max_length=48)),
                ('pdf_file', models.FileField(blank=True, upload_to='projects/pdfs')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['pdf_num'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['image_num']},
        ),
    ]
