# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20161205_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Sub Project short name')),
                ('title', models.CharField(max_length=48)),
                ('body_text', models.TextField(blank=True, default='')),
                ('key_action_id', models.IntegerField(blank=True, null=True)),
                ('status_num', models.IntegerField(choices=[(0, '0 - Draft'), (1, '1 - Display')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
