# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_subproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubprojectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_num', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='subprojects')),
                ('credit', models.CharField(blank=True, default='', max_length=64, verbose_name='Image credit')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Subproject')),
            ],
            options={
                'ordering': ['image_num'],
            },
        ),
        migrations.CreateModel(
            name='SubprojectPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_num', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, upload_to='subprojects/pdfs')),
                ('title', models.CharField(max_length=48)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Subproject')),
            ],
            options={
                'ordering': ['pdf_num'],
            },
        ),
    ]
