# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_subprojectimage_subprojectpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojectimage',
            name='image_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subprojectpdf',
            name='pdf_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
