# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180528_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='projectpdf',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subprojectpdf',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
