# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-posted']},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='menu',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='sitewide.Menu'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
