# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161127_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - on home page'), (2, '2 - current'), (3, '3 - archived'), (4, '4 - inactive')], default=2),
        ),
    ]
