# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Organization short name')),
                ('name', models.CharField(max_length=128)),
                ('link_url', models.CharField(blank=True, default='', max_length=128)),
                ('town', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
            ],
        ),
    ]
