# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Organization short name')),
                ('title', models.CharField(max_length=128)),
                ('body_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['id']},
        ),
    ]
