# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20161111_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcepage',
            options={'ordering': ['ordinal']},
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Order in Menu'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Resource page short name'),
        ),
    ]
