# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20161111_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
