# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20161116_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Order in Menu'),
        ),
    ]
