# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20161205_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='resources/pdfs')),
            ],
        ),
    ]
