# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20161215_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='plain_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
